// Tên tiếng Anh của các dòng model forecast (MODEL_ROWS trong model.js), khoá là số dòng 03.Input_FS.
// tests/i18n.test.js kiểm tra khớp một-một với MODEL_ROWS. (Tên nhóm dòng nằm ở i18n: khoá mgroup.*)

export const MODEL_EN = {
  8: 'Net revenue',
  9: 'Cost of goods sold (−)',
  12: 'Financial income',
  13: 'Interest expense (−)',
  14: 'Other financial expenses (−)',
  16: 'Profit/loss from joint ventures and associates',
  17: 'Selling expenses (−)',
  18: 'General and administrative expenses (−)',
  20: 'Other income (incl. gains on investment property)',
  21: 'Other expenses (−)',
  23: 'Current corporate income tax (−)',
  24: 'Deferred corporate income tax',
  27: 'Profit after tax attributable to non-controlling interests',
  32: 'Cash',
  33: 'Cash equivalents',
  34: 'Short-term financial investments',
  36: 'Short-term trade receivables',
  37: 'Short-term prepayments to suppliers',
  38: 'Short-term loan receivables',
  39: 'Other short-term receivables (+ other current assets)',
  40: 'Provision for doubtful short-term receivables (−)',
  42: 'Inventories',
  43: 'Provision for devaluation of inventories (−)',
  45: 'Short-term prepaid expenses',
  46: 'Deductible value added tax',
  47: 'Taxes receivable from the State',
  52: 'Long-term receivables',
  54: 'Tangible fixed assets — cost (incl. finance leases)',
  55: 'Tangible fixed assets — accumulated depreciation (−)',
  57: 'Intangible fixed assets — cost',
  58: 'Intangible fixed assets — accumulated amortisation (−)',
  59: 'Long-term assets in progress',
  60: 'Investments in joint ventures and associates',
  61: 'Other long-term financial investments',
  62: 'Long-term prepaid expenses',
  63: 'Deferred income tax assets',
  64: 'Other non-current assets (+ investment property, biological assets)',
  65: 'Goodwill',
  71: 'Short-term trade payables',
  72: 'Short-term advances from customers',
  73: 'Taxes payable to the State',
  74: 'Payables to employees',
  75: 'Short-term accrued expenses',
  76: 'Short-term deferred revenue',
  77: 'Other payables (+ dividends, provisions, welfare fund…)',
  78: 'Short-term borrowings and finance lease liabilities',
  80: 'Long-term borrowings and finance lease liabilities',
  81: 'Deferred income tax liabilities',
  82: 'Other long-term liabilities',
  85: 'Contributed charter capital',
  86: 'Share premium',
  87: 'Treasury shares (−)',
  88: 'Investment and development fund (+ other capital and funds)',
  89: 'Undistributed profit after tax',
  90: 'Non-controlling interests',
  98: 'Depreciation and amortisation',
  99: 'Provisions',
  100: '(Profit) from joint ventures and associates',
  101: 'Interest expense',
  103: 'Change in receivables',
  104: 'Change in inventories',
  105: 'Change in payables',
  106: 'Change in prepaid expenses',
  107: 'Interest paid',
  108: 'Corporate income tax paid',
  109: 'Other operating receipts/payments (balancing line)',
  112: 'Purchases of fixed assets (capex)',
  113: 'Disposals of fixed assets',
  114: 'Equity investments in other entities',
  115: 'Other investing receipts/payments (balancing line)',
  118: 'Share issues',
  119: 'Share repurchases',
  122: 'Dividends paid',
  123: 'Other financing receipts/payments (balancing line)',
  126: 'Cash at beginning of period',
  127: 'Effect of exchange rate changes',
  132: 'Revenue — segment 1',
  133: 'Revenue — segment 2',
  134: 'Revenue — segment 3',
  135: 'Revenue — segment 4',
  136: 'Revenue — segment 5',
  140: 'Gross profit — segment 1',
  141: 'Gross profit — segment 2',
  142: 'Gross profit — segment 3',
  143: 'Gross profit — segment 4',
  144: 'Gross profit — segment 5',
  150: 'Buildings and structures — cost',
  151: 'Buildings and structures — accumulated depreciation (−)',
  152: 'Buildings and structures — additions in the year',
  153: 'Buildings and structures — depreciation for the year (−)',
  155: 'Machinery and equipment — cost',
  156: 'Machinery and equipment — accumulated depreciation (−)',
  157: 'Machinery and equipment — additions in the year',
  158: 'Machinery and equipment — depreciation for the year (−)',
  160: 'Vehicles — cost',
  161: 'Vehicles — accumulated depreciation (−)',
  162: 'Vehicles — additions in the year',
  163: 'Vehicles — depreciation for the year (−)',
  165: 'Office equipment — cost',
  166: 'Office equipment — accumulated depreciation (−)',
  167: 'Office equipment — additions in the year',
  168: 'Office equipment — depreciation for the year (−)',
  170: 'Other tangible fixed assets (incl. finance leases) — cost',
  171: 'Other tangible fixed assets (incl. finance leases) — accumulated depreciation (−)',
  172: 'Other tangible fixed assets (incl. finance leases) — additions in the year',
  173: 'Other tangible fixed assets (incl. finance leases) — depreciation for the year (−)',
  175: 'Land use rights — cost',
  176: 'Land use rights — accumulated amortisation (−)',
  177: 'Land use rights — additions in the year',
  178: 'Land use rights — amortisation for the year (−)',
  180: 'Software and other intangibles — cost',
  181: 'Software and other intangibles — accumulated amortisation (−)',
  182: 'Software and other intangibles — additions in the year',
  183: 'Software and other intangibles — amortisation for the year (−)',
  185: 'Goodwill — cost',
  186: 'Goodwill — accumulated amortisation (−)',
  187: 'Goodwill — additions in the year',
  188: 'Goodwill — amortisation for the year (−)',
  191: 'Charter capital — ordinary issue',
  192: 'Charter capital — bonus shares',
  193: 'Charter capital — ESOP',
  194: 'Charter capital — stock dividend',
  195: 'Charter capital — decrease',
  196: 'Share premium — increase',
  197: 'Share premium — decrease',
  198: 'Treasury shares — increase (−)',
  199: 'Treasury shares — decrease',
  200: 'Investment and development fund — increase',
  201: 'Investment and development fund — decrease',
  202: 'Retained earnings — dividends declared (−)',
  203: 'Retained earnings — other increases',
  204: 'Retained earnings — other decreases (−)',
  205: 'Non-controlling interests — change from consolidation',
  208: 'Short-term borrowings — proceeds',
  209: 'Short-term borrowings — repayments (−)',
  210: 'Long-term borrowings — proceeds',
  211: 'Long-term borrowings — repayments (−)',
  214: 'Shares outstanding (million shares)',
  215: 'Share price (VND)',
  216: 'Corporate income tax rate',
  217: 'Goodwill amortisation period (years)',
};
