// Tên tiếng Anh của từng chỉ tiêu trong CHART (chart2026.js) — dùng khi người dùng chọn ngôn ngữ English.
// Khoá là `${st}:${code}`, khớp một-một với CHART; tests/i18n.test.js kiểm tra không thiếu, không thừa.
// Tên theo cách gọi quen thuộc trong BCTC song ngữ của doanh nghiệp niêm yết Việt Nam.

export const CHART_EN = {
  // ── Báo cáo tình hình tài chính ──
  'BS:100': 'A. CURRENT ASSETS',
  'BS:110': 'I. Cash and cash equivalents',
  'BS:111': '1. Cash',
  'BS:111a': '¤ Cash on hand',
  'BS:111b': '¤ Cash in banks',
  'BS:112': '2. Cash equivalents',
  'BS:120': 'II. Short-term financial investments',
  'BS:121': '1. Trading securities',
  'BS:122': '2. Provision for devaluation of trading securities (*)',
  'BS:123': '3. Short-term held-to-maturity investments',
  'BS:124': '4. Provision for short-term held-to-maturity investments (*)',
  'BS:125': '5. Other short-term investments',
  'BS:126': '6. Provision for loss on other short-term investments (*)',
  'BS:130': 'III. Short-term receivables',
  'BS:131': '1. Short-term trade receivables',
  'BS:132': '2. Short-term prepayments to suppliers',
  'BS:133': '3. Short-term intercompany receivables',
  'BS:134': '4. Receivables under construction contract schedule',
  'BS:135x': '5. Short-term loan receivables',
  'BS:135': '6. Other short-term receivables',
  'BS:136': '7. Provision for doubtful short-term receivables (*)',
  'BS:137': '8. Shortage of assets awaiting resolution',
  'BS:140': 'IV. Inventories',
  'BS:141': '1. Inventories',
  'BS:141a': '¤ Goods in transit',
  'BS:141b': '¤ Raw materials',
  'BS:141c': '¤ Tools and supplies',
  'BS:141d': '¤ Work in progress',
  'BS:141e': '¤ Finished goods',
  'BS:141f': '¤ Merchandise',
  'BS:141g': '¤ Goods on consignment',
  'BS:142': '2. Provision for devaluation of inventories (*)',
  'BS:150': 'V. Short-term biological assets',
  'BS:151': '1. Short-term livestock held for single harvest',
  'BS:152': '2. Short-term seasonal / single-harvest crops',
  'BS:153': '3. Provision for loss on short-term biological assets (*)',
  'BS:160': 'VI. Other current assets',
  'BS:161': '1. Short-term costs awaiting allocation',
  'BS:162': '2. Deductible value added tax',
  'BS:163': '3. Taxes and other receivables from the State',
  'BS:164': '4. Government bond repurchase transactions',
  'BS:165': '5. Other current assets',
  'BS:200': 'B. NON-CURRENT ASSETS',
  'BS:210': 'I. Long-term receivables',
  'BS:211': '1. Long-term trade receivables',
  'BS:212': '2. Long-term prepayments to suppliers',
  'BS:213': '3. Working capital provided to subsidiaries',
  'BS:214': '4. Long-term intercompany receivables',
  'BS:215x': '5. Long-term loan receivables',
  'BS:215': '6. Other long-term receivables',
  'BS:216': '7. Provision for doubtful long-term receivables (*)',
  'BS:220': 'II. Fixed assets',
  'BS:221': '1. Tangible fixed assets',
  'BS:222': '- Historical cost',
  'BS:223': '- Accumulated depreciation (*)',
  'BS:224': '2. Finance lease fixed assets',
  'BS:225': '- Historical cost',
  'BS:226': '- Accumulated depreciation (*)',
  'BS:227': '3. Intangible fixed assets',
  'BS:228': '- Historical cost',
  'BS:229': '- Accumulated amortisation (*)',
  'BS:230': 'III. Long-term biological assets',
  'BS:231': '1. Livestock held for repeated produce',
  'BS:232': 'a) Immature livestock',
  'BS:233': 'b) Mature livestock',
  'BS:234': '- Historical cost',
  'BS:235': '- Accumulated depreciation (*)',
  'BS:236': '2. Long-term livestock held for single harvest',
  'BS:237': '3. Long-term seasonal / single-harvest crops',
  'BS:238': '4. Provision for loss on long-term biological assets (*)',
  'BS:240': 'IV. Investment properties',
  'BS:241': '- Historical cost',
  'BS:242': '- Accumulated depreciation (*)',
  'BS:250': 'V. Long-term assets in progress',
  'BS:251': '1. Long-term production and business costs in progress',
  'BS:252': '2. Construction in progress',
  'BS:260': 'VI. Long-term financial investments',
  'BS:261': '1. Investments in subsidiaries',
  'BS:262': '2. Investments in joint ventures and associates',
  'BS:263': '3. Equity investments in other entities',
  'BS:264': '4. Provision for loss on long-term investments in other entities (*)',
  'BS:265': '5. Long-term held-to-maturity investments',
  'BS:266': '6. Provision for long-term held-to-maturity investments (*)',
  'BS:270': 'VII. Other non-current assets',
  'BS:271': '1. Long-term prepaid expenses',
  'BS:272': '2. Deferred income tax assets',
  'BS:273': '3. Long-term equipment, materials and spare parts',
  'BS:274': '4. Other non-current assets',
  'BS:279': '5. Goodwill',
  'BS:280': 'TOTAL ASSETS',
  'BS:300': 'C. LIABILITIES',
  'BS:310': 'I. Current liabilities',
  'BS:311': '1. Short-term trade payables',
  'BS:312': '2. Short-term advances from customers',
  'BS:313': '3. Dividends and profits payable',
  'BS:314': '4. Short-term taxes and payables to the State',
  'BS:315': '5. Payables to employees',
  'BS:316': '6. Short-term accrued expenses',
  'BS:317': '7. Short-term intercompany payables',
  'BS:318': '8. Short-term payables under construction contract schedule',
  'BS:319': '9. Short-term deferred revenue',
  'BS:320': '10. Other short-term payables',
  'BS:321': '11. Short-term borrowings and finance lease liabilities',
  'BS:321a': '- Short-term borrowings from credit institutions',
  'BS:321b': '- Other short-term borrowings',
  'BS:322': '12. Short-term provisions',
  'BS:323': '13. Bonus and welfare fund',
  'BS:324': '14. Price stabilisation fund',
  'BS:325': '15. Government bond repurchase transactions',
  'BS:330': 'II. Non-current liabilities',
  'BS:331': '1. Long-term trade payables',
  'BS:332': '2. Long-term advances from customers',
  'BS:333': '3. Long-term taxes and payables to the State',
  'BS:334': '4. Long-term accrued expenses',
  'BS:335': '5. Intercompany payables on working capital',
  'BS:336': '6. Long-term intercompany payables',
  'BS:337': '7. Long-term deferred revenue',
  'BS:338': '8. Other long-term payables',
  'BS:339': '9. Long-term borrowings and finance lease liabilities',
  'BS:339a': '- Long-term borrowings from credit institutions',
  'BS:339b': '- Other long-term borrowings from entities / individuals',
  'BS:340': '10. Convertible bonds',
  'BS:341': '11. Preference shares',
  'BS:342': '12. Deferred income tax liabilities',
  'BS:343': '13. Long-term provisions',
  'BS:344': '14. Science and technology development fund',
  'BS:400': "D. OWNERS' EQUITY",
  'BS:410': "I. Owners' equity",
  'BS:411': '1. Contributed charter capital',
  'BS:411a': '¤ Ordinary shares with voting rights',
  'BS:411b': '¤ Preference shares',
  'BS:412': '2. Share premium',
  'BS:413': '3. Bond conversion options',
  'BS:414': "4. Other owners' capital",
  'BS:415': '5. Treasury shares (*)',
  'BS:416': '6. Asset revaluation differences',
  'BS:417': '7. Foreign exchange differences',
  'BS:418': '8. Investment and development fund',
  'BS:419x': '9. Enterprise restructuring support fund',
  'BS:419': "10. Other funds belonging to owners' equity",
  'BS:420': '11. Undistributed profit after tax',
  'BS:420a': '¤ Accumulated undistributed profit to prior period end',
  'BS:420b': '¤ Undistributed profit of the current period',
  'BS:429': '12. Non-controlling interests',
  'BS:441': '13. Capital for basic construction investment',
  'BS:KPQ': 'II. Funding sources and other funds',
  'BS:KP1': '1. Funding sources',
  'BS:KP2': '2. Funding used for fixed asset acquisition',
  'BS:440': "TOTAL LIABILITIES AND OWNERS' EQUITY",

  // ── Báo cáo kết quả hoạt động kinh doanh ──
  'IS:01': '1. Revenue from sales of goods and rendering of services',
  'IS:02': '2. Revenue deductions',
  'IS:10': '3. Net revenue from sales of goods and rendering of services',
  'IS:11': '4. Cost of goods sold',
  'IS:20': '5. Gross profit from sales of goods and rendering of services',
  'IS:21': '6. Gain/loss on sale and disposal of investment properties',
  'IS:22': '7. Financial income',
  'IS:23': '8. Financial expenses',
  'IS:24': 'In which: Interest expense (borrowing costs)',
  'IS:25': '9. Selling expenses',
  'IS:26': '10. General and administrative expenses',
  'IS:27': 'Share of profit/loss in joint ventures and associates (consolidated)',
  'IS:30': '11. Net operating profit',
  'IS:31': '12. Other income',
  'IS:32': '13. Other expenses',
  'IS:40': '14. Other profit',
  'IS:50': '15. Accounting profit before tax',
  'IS:51': '16. Current corporate income tax expense',
  'IS:52': '17. Deferred corporate income tax expense',
  'IS:60': '18. Profit after corporate income tax',
  'IS:61': 'Profit after tax attributable to the parent (consolidated)',
  'IS:62': 'Profit after tax attributable to non-controlling interests (consolidated)',
  'IS:70': '19. Basic earnings per share (*)',
  'IS:71': '20. Diluted earnings per share (*)',

  // ── Báo cáo lưu chuyển tiền tệ — phương pháp gián tiếp ──
  'CF:01': '1. Profit before tax',
  'CF:02': '- Depreciation of fixed assets and investment properties',
  'CF:03': '- Provisions',
  'CF:04': '- Foreign exchange gains/losses',
  'CF:05': '- Gains/losses from investing activities',
  'CF:06': '- Borrowing costs',
  'CF:07': '- Other adjustments',
  'CF:08': '3. Operating profit before changes in working capital',
  'CF:09': '- Increase/decrease in receivables',
  'CF:10': '- Increase/decrease in inventories',
  'CF:11': '- Increase/decrease in payables',
  'CF:12': '- Increase/decrease in costs awaiting allocation',
  'CF:13': '- Increase/decrease in trading securities',
  'CF:14': '- Borrowing costs paid',
  'CF:15': '- Corporate income tax paid',
  'CF:16': '- Other receipts from operating activities',
  'CF:17': '- Other payments for operating activities',
  'CF:20': 'Net cash flows from operating activities',
  'CF:21': '1. Purchases and construction of fixed assets',
  'CF:22': '2. Proceeds from disposal of fixed assets',
  'CF:23': '3. Loans granted and purchases of debt instruments',
  'CF:24': '4. Collection of loans and resale of debt instruments',
  'CF:25': '5. Equity investments in other entities',
  'CF:26': '6. Withdrawal of equity investments in other entities',
  'CF:27': '7. Interest, dividends and profits received',
  'CF:30': 'Net cash flows from investing activities',
  'CF:31': '1. Proceeds from share issues and capital contributions',
  'CF:32': '2. Payments for repurchase of issued shares',
  'CF:33': '3. Proceeds from short-term and long-term borrowings',
  'CF:34': '4. Repayments of borrowing principal',
  'CF:35': '5. Payments of finance lease principal',
  'CF:36': '6. Dividends and profits paid to owners',
  'CF:40': 'Net cash flows from financing activities',
  'CF:50': 'Net cash flows during the period',
  'CF:60': 'Cash and cash equivalents at beginning of period',
  'CF:61': 'Effect of exchange rate changes',
  'CF:70': 'Cash and cash equivalents at end of period',

  // ── Báo cáo lưu chuyển tiền tệ — phương pháp trực tiếp ──
  'CF:T01': '1. Receipts from sales of goods, services and other income',
  'CF:T02': '2. Payments to suppliers for goods and services',
  'CF:T03': '3. Payments to employees',
  'CF:T04': '4. Interest paid',
  'CF:T05': '5. Corporate income tax paid',
  'CF:T06': '6. Other receipts from operating activities',
  'CF:T07': '7. Other payments for operating activities',
  'CF:T20': 'Net cash flows from operating activities',
  'CF:T21': '1. Purchases and construction of fixed assets',
  'CF:T22': '2. Proceeds from disposal of fixed assets',
  'CF:T23': '3. Loans granted and purchases of debt instruments',
  'CF:T24': '4. Collection of loans and resale of debt instruments',
  'CF:T25': '5. Equity investments in other entities',
  'CF:T26': '6. Withdrawal of equity investments in other entities',
  'CF:T27': '7. Interest, dividends and profits received',
  'CF:T30': 'Net cash flows from investing activities',
  'CF:T31': '1. Proceeds from share issues and capital contributions',
  'CF:T32': '2. Payments of capital and repurchase of shares',
  'CF:T33': '3. Proceeds from short-term and long-term borrowings',
  'CF:T34': '4. Repayments of borrowing principal',
  'CF:T35': '5. Payments of finance lease principal',
  'CF:T36': '6. Dividends and profits paid to owners',
  'CF:T40': 'Net cash flows from financing activities',
  'CF:T50': 'Net cash flows during the period',
  'CF:T60': 'Cash and cash equivalents at beginning of period',
  'CF:T61': 'Effect of exchange rate changes',
  'CF:T70': 'Cash and cash equivalents at end of period',
};
